CFLAGS = 
#LIBS = -lpthread -lrt -lm
LIBS = -lpthread -lm
SOURCES = project1.c scheduler.c 
OUT = out
default:
	gcc -g $(SOURCES) $(LIBS) -o $(OUT)
all:
	gcc $(SOURCES) $(LIBS) -o $(OUT)
clean:
	rm $(OUT)
